Initializing various ws definitions in SetupSuite
Instead of parsing and creating the various ws definitions used for testing during file initialization, doing this work in SetupSuite. This makes it easier to see parsing errors, and pinpoint where they come from. Which is handy as we work on the parser! Before this change, a panic in `MustNewDefinitions` would yield

	panic: test

	goroutine 1 [running]:
	github.com/helloeave/worksheets.MustNewDefinitions(0x156a760, 0xc4201ac1a0, 0x0, 0x0, 0x0, 0xc4200943d0)
		/Users/pascal/Development/go/src/github.com/helloeave/worksheets/worksheets.go:109 +0x39
	FAIL	github.com/helloeave/worksheets	0.018s
	ok  	github.com/helloeave/worksheets/tools	(cached)

whereas now it yields

	--- FAIL: TestRunAllTheDbTests (0.00s)
	panic: test [recovered]
		panic: test

	goroutine 5 [running]:
	testing.tRunner.func1(0xc4201942d0)
		/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:742 +0x29d
	panic(0x1457a40, 0x1568b00)
		/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
	github.com/helloeave/worksheets.MustNewDefinitions(0x156b1a0, 0xc420196240, 0x0, 0x0, 0x0, 0x1)
		/Users/pascal/Development/go/src/github.com/helloeave/worksheets/worksheets.go:109 +0x39
	github.com/helloeave/worksheets.newAllDefs(0x0, 0x0, 0x0, 0x0, 0x0)
		/Users/pascal/Development/go/src/github.com/helloeave/worksheets/testutil_test.go:83 +0xec
	github.com/helloeave/worksheets.(*DbZuite).SetupSuite(0xc4200a18b0)
		/Users/pascal/Development/go/src/github.com/helloeave/worksheets/dbtestutil_test.go:35 +0x26
	github.com/stretchr/testify/suite.Run(0xc4201942d0, 0x156cda0, 0xc4200a18b0)
		/Users/pascal/Development/go/src/github.com/stretchr/testify/suite/suite.go:64 +0x588
	github.com/helloeave/worksheets.TestRunAllTheDbTests(0xc4201942d0)
		/Users/pascal/Development/go/src/github.com/helloeave/worksheets/dbtestutil_test.go:86 +0x51
	testing.tRunner(0xc4201942d0, 0x152c7b8)
		/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:777 +0xd0
	created by testing.(*T).Run
		/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:824 +0x2e0

which properly identifies `dbtestutil_test.go:86` as the culprit.